Resources:
  database:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      DBInstanceIdentifier: helloworld
      DBInstanceClass: db.t2.micro
      DBName: helloworld
      Engine: postgres
      MasterUsername: postgres
      MasterUserPassword: postgres
    DeletionPolicy: Snapshot